server:
  port: 8085
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
cloud:
  gateway:
    discovery:
      locator:
        enabled: true